# -*- coding: utf-8 -*-
"""[Jobsgo][Pipeline Region].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-HYzEsD23Ph2Pvd3k_bgEQCT9yiO0JY
"""

!pip install gspread pandas oauth2client

import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials
import json
from google.colab import userdata

# Get the service account key from Colab Secrets
service_account_info = json.loads(userdata.get('SERVICE_ACCOUNT_JSON'))

# Authenticate Google Sheets API
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_dict(service_account_info, scope)
client = gspread.authorize(creds)

# Open Google Sheet
# Replace "Tên_Google_Sheet" with your Google Sheet name
# Replace "Tên_Sheet" with your sheet name
spreadsheet = client.open_by_url("https://docs.google.com/spreadsheets/d/1RNrJ5B3pzLGNmxir2EguHH55vGUNHAOzaOV6Ng6_fVI/edit?gid=843162208#gid=843162208")
sheet = spreadsheet.worksheet("Jobs 2025")
data = sheet.get_all_records()
# Convert to DataFrame
df = pd.DataFrame(data)
print(df.head())

def assign_region(places_str):
    if pd.isna(places_str):
        return 'Không rõ'

    places = [p.strip() for p in places_str.split(',') if p.strip()]

    # Từ khoá miền
    north_keywords = ['Hà Nội', 'Hải Phòng', 'Quảng Ninh', 'Bắc Ninh', 'Hưng Yên', 'Hải Dương',
                      'Thái Nguyên', 'Vĩnh Phúc', 'Phú Thọ', 'Bắc Giang', 'Thái Bình', 'Nam Định',
                      'Hà Nam', 'Ninh Bình', 'Hòa Bình', 'Sơn La', 'Lai Châu', 'Điện Biên',
                      'Lào Cai', 'Yên Bái', 'Tuyên Quang', 'Cao Bằng', 'Bắc Kạn', 'Lạng Sơn',
                      'Quảng Trị', 'Thừa Thiên Huế']

    central_keywords = ['Đà Nẵng', 'Quảng Nam', 'Quảng Ngãi', 'Bình Định', 'Phú Yên',
                        'Khánh Hòa', 'Ninh Thuận', 'Bình Thuận', 'Thanh Hóa', 'Nghệ An',
                        'Hà Tĩnh', 'Quảng Bình', 'Gia Lai', 'Kon Tum', 'Đắk Lắk',
                        'Đắk Nông', 'Lâm Đồng']

    south_keywords = ['Hồ Chí Minh', 'Sài Gòn', 'TP.HCM', 'Bình Dương', 'Đồng Nai', 'Bà Rịa - Vũng Tàu',
                      'Tây Ninh', 'Bình Phước']

    south_west_keywords = ['Long An', 'Tiền Giang', 'Bến Tre', 'Trà Vinh', 'Vĩnh Long',
                           'Đồng Tháp', 'An Giang', 'Kiên Giang', 'Cần Thơ', 'Hậu Giang',
                           'Sóc Trăng', 'Bạc Liêu', 'Cà Mau']

    regions = []

    for place in places:
        found = False

        for keyword in north_keywords:
            if keyword.lower() in place.lower():
                regions.append('Miền Bắc')
                found = True
                break
        if found: continue

        for keyword in central_keywords:
            if keyword.lower() in place.lower():
                regions.append('Miền Trung')
                found = True
                break
        if found: continue

        for keyword in south_west_keywords:
            if keyword.lower() in place.lower():
                regions.append('Miền Tây')
                found = True
                break
        if found: continue

        for keyword in south_keywords:
            if keyword.lower() in place.lower():
                regions.append('Miền Nam')
                found = True
                break
        # ⚠️ Không còn append 'Không rõ' ở đây

    # Loại trùng & loại 'Không rõ' nếu có sót
    unique_regions = list(set(regions))

    if len(places) == 1:
        return places[0]
    elif len(unique_regions) == 0:
        return 'Không rõ'
    elif len(unique_regions) == 1:
        return unique_regions[0]
    elif len(unique_regions) == 2:
        return ', '.join(sorted(unique_regions))
    elif len(unique_regions) >= 3:
        return 'Toàn quốc'
    else:
        return 'Không rõ'
df['Region'] = df['Places'].apply(assign_region)

df

# Xuất DataFrame df sang Google Sheets
spreadsheet = client.open_by_url("https://docs.google.com/spreadsheets/d/1E5EkOL7EJWQloDixisDQBN0mlVMBu4WC3MBgp4ze6cc/edit?gid=612484126#gid=612484126")
worksheet = spreadsheet.worksheet("Jobs 2025")      # tab đầu tiên
worksheet.clear()                                # xoá dữ liệu cũ
worksheet.update([df.columns.values.tolist()] + df.values.tolist())

print("✅ Đã ghi dữ liệu thành công lên Google Sheets!")

